// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Registration.proto

#include "Registration.pb.h"
#include "Registration.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace request_proto {

static const char* Registration_method_names[] = {
  "/request_proto.Registration/GetRegisterInfo",
};

std::unique_ptr< Registration::Stub> Registration::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Registration::Stub> stub(new Registration::Stub(channel));
  return stub;
}

Registration::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetRegisterInfo_(Registration_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Registration::Stub::GetRegisterInfo(::grpc::ClientContext* context, const ::request_proto::Empty& request, ::request_proto::RegisterInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::request_proto::Empty, ::request_proto::RegisterInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRegisterInfo_, context, request, response);
}

void Registration::Stub::experimental_async::GetRegisterInfo(::grpc::ClientContext* context, const ::request_proto::Empty* request, ::request_proto::RegisterInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::request_proto::Empty, ::request_proto::RegisterInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRegisterInfo_, context, request, response, std::move(f));
}

void Registration::Stub::experimental_async::GetRegisterInfo(::grpc::ClientContext* context, const ::request_proto::Empty* request, ::request_proto::RegisterInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRegisterInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::request_proto::RegisterInfo>* Registration::Stub::PrepareAsyncGetRegisterInfoRaw(::grpc::ClientContext* context, const ::request_proto::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::request_proto::RegisterInfo, ::request_proto::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRegisterInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::request_proto::RegisterInfo>* Registration::Stub::AsyncGetRegisterInfoRaw(::grpc::ClientContext* context, const ::request_proto::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRegisterInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

Registration::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Registration_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Registration::Service, ::request_proto::Empty, ::request_proto::RegisterInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Registration::Service* service,
             ::grpc::ServerContext* ctx,
             const ::request_proto::Empty* req,
             ::request_proto::RegisterInfo* resp) {
               return service->GetRegisterInfo(ctx, req, resp);
             }, this)));
}

Registration::Service::~Service() {
}

::grpc::Status Registration::Service::GetRegisterInfo(::grpc::ServerContext* context, const ::request_proto::Empty* request, ::request_proto::RegisterInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace request_proto

