// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Regulator.proto
#ifndef GRPC_Regulator_2eproto__INCLUDED
#define GRPC_Regulator_2eproto__INCLUDED

#include "Regulator.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace request_proto {

class Regulator final {
 public:
  static constexpr char const* service_full_name() {
    return "request_proto.Regulator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>> GetComplianceProof(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>>(GetComplianceProofRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>> AsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>>(AsyncGetComplianceProofRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>> PrepareAsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>>(PrepareAsyncGetComplianceProofRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetComplianceProof(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::request_proto::ProofRequest,::request_proto::ProofResponse>* reactor) = 0;
      #else
      virtual void GetComplianceProof(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::request_proto::ProofRequest,::request_proto::ProofResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* GetComplianceProofRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* AsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* PrepareAsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>> GetComplianceProof(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>>(GetComplianceProofRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>> AsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>>(AsyncGetComplianceProofRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>> PrepareAsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>>(PrepareAsyncGetComplianceProofRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetComplianceProof(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::request_proto::ProofRequest,::request_proto::ProofResponse>* reactor) override;
      #else
      void GetComplianceProof(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::request_proto::ProofRequest,::request_proto::ProofResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* GetComplianceProofRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* AsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* PrepareAsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetComplianceProof_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetComplianceProof(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetComplianceProof() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetComplianceProof(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetComplianceProof<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetComplianceProof() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::request_proto::ProofRequest, ::request_proto::ProofResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->GetComplianceProof(context); }));
    }
    ~ExperimentalWithCallbackMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* GetComplianceProof(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::request_proto::ProofRequest, ::request_proto::ProofResponse>* GetComplianceProof(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetComplianceProof<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetComplianceProof<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetComplianceProof() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetComplianceProof() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetComplianceProof(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetComplianceProof() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->GetComplianceProof(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::request_proto::ProofResponse, ::request_proto::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* GetComplianceProof(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* GetComplianceProof(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace request_proto


#endif  // GRPC_Regulator_2eproto__INCLUDED
