// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Regulator.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_Regulator_2eproto__INCLUDED
#define GRPC_Regulator_2eproto__INCLUDED

#include "Regulator.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace protos {

// The regulator service definition for external use, i.e., intra-peer (gRPC 1).
// This service defines methods for regulatory compliance check, both
// in synchronous and asynchronous ways, i.e., 1) a "CheckCompliance"
// method for synchronous compliance check and 2) an "AsyncCheckCompliance"
// method for asynchronous check.
class Regulator final {
 public:
  static constexpr char const* service_full_name() {
    return "protos.Regulator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // This is the only method needed for gRPC2, where we keep a bidirectional
    // stream between both communicating parties.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>> GetComplianceProof(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>>(GetComplianceProofRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>> AsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>>(AsyncGetComplianceProofRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>> PrepareAsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>>(PrepareAsyncGetComplianceProofRaw(context, cq));
    }
    // Retrieve registration materials from compliance-node-sgx, i.e,
    // 1) pkbase64; 2) quotebase64
    virtual ::grpc::Status GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty& request, ::protos::RegisterInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::RegisterInfo>> AsyncGetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::RegisterInfo>>(AsyncGetRegisterInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::RegisterInfo>> PrepareAsyncGetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::RegisterInfo>>(PrepareAsyncGetRegisterInfoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // This is the only method needed for gRPC2, where we keep a bidirectional
      // stream between both communicating parties.
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetComplianceProof(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::protos::ProofRequest,::protos::ProofResponse>* reactor) = 0;
      #else
      virtual void GetComplianceProof(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::protos::ProofRequest,::protos::ProofResponse>* reactor) = 0;
      #endif
      // Retrieve registration materials from compliance-node-sgx, i.e,
      // 1) pkbase64; 2) quotebase64
      virtual void GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>* GetComplianceProofRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>* AsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::protos::ProofRequest, ::protos::ProofResponse>* PrepareAsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protos::RegisterInfo>* AsyncGetRegisterInfoRaw(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protos::RegisterInfo>* PrepareAsyncGetRegisterInfoRaw(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>> GetComplianceProof(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>>(GetComplianceProofRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>> AsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>>(AsyncGetComplianceProofRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>> PrepareAsyncGetComplianceProof(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>>(PrepareAsyncGetComplianceProofRaw(context, cq));
    }
    ::grpc::Status GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty& request, ::protos::RegisterInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::RegisterInfo>> AsyncGetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::RegisterInfo>>(AsyncGetRegisterInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::RegisterInfo>> PrepareAsyncGetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::RegisterInfo>>(PrepareAsyncGetRegisterInfoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetComplianceProof(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::protos::ProofRequest,::protos::ProofResponse>* reactor) override;
      #else
      void GetComplianceProof(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::protos::ProofRequest,::protos::ProofResponse>* reactor) override;
      #endif
      void GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetRegisterInfo(::grpc::ClientContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>* GetComplianceProofRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>* AsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::protos::ProofRequest, ::protos::ProofResponse>* PrepareAsyncGetComplianceProofRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protos::RegisterInfo>* AsyncGetRegisterInfoRaw(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protos::RegisterInfo>* PrepareAsyncGetRegisterInfoRaw(::grpc::ClientContext* context, const ::protos::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetComplianceProof_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRegisterInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // This is the only method needed for gRPC2, where we keep a bidirectional
    // stream between both communicating parties.
    virtual ::grpc::Status GetComplianceProof(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* stream);
    // Retrieve registration materials from compliance-node-sgx, i.e,
    // 1) pkbase64; 2) quotebase64
    virtual ::grpc::Status GetRegisterInfo(::grpc::ServerContext* context, const ::protos::Empty* request, ::protos::RegisterInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetComplianceProof() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetComplianceProof(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRegisterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRegisterInfo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetRegisterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRegisterInfo(::grpc::ServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRegisterInfo(::grpc::ServerContext* context, ::protos::Empty* request, ::grpc::ServerAsyncResponseWriter< ::protos::RegisterInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetComplianceProof<WithAsyncMethod_GetRegisterInfo<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetComplianceProof() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::protos::ProofRequest, ::protos::ProofResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->GetComplianceProof(context); }));
    }
    ~ExperimentalWithCallbackMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::protos::ProofRequest, ::protos::ProofResponse>* GetComplianceProof(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::protos::ProofRequest, ::protos::ProofResponse>* GetComplianceProof(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetRegisterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetRegisterInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::protos::Empty, ::protos::RegisterInfo>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::protos::Empty* request, ::protos::RegisterInfo* response) { return this->GetRegisterInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetRegisterInfo(
        ::grpc::experimental::MessageAllocator< ::protos::Empty, ::protos::RegisterInfo>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::protos::Empty, ::protos::RegisterInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetRegisterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRegisterInfo(::grpc::ServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetRegisterInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetRegisterInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetComplianceProof<ExperimentalWithCallbackMethod_GetRegisterInfo<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetComplianceProof<ExperimentalWithCallbackMethod_GetRegisterInfo<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetComplianceProof() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRegisterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRegisterInfo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetRegisterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRegisterInfo(::grpc::ServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetComplianceProof() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetComplianceProof(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRegisterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRegisterInfo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetRegisterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRegisterInfo(::grpc::ServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRegisterInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetComplianceProof : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetComplianceProof() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->GetComplianceProof(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetComplianceProof() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetComplianceProof(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::protos::ProofResponse, ::protos::ProofRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* GetComplianceProof(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* GetComplianceProof(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetRegisterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetRegisterInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRegisterInfo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetRegisterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRegisterInfo(::grpc::ServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetRegisterInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetRegisterInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRegisterInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRegisterInfo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protos::Empty, ::protos::RegisterInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::protos::Empty, ::protos::RegisterInfo>* streamer) {
                       return this->StreamedGetRegisterInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRegisterInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRegisterInfo(::grpc::ServerContext* /*context*/, const ::protos::Empty* /*request*/, ::protos::RegisterInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRegisterInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protos::Empty,::protos::RegisterInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetRegisterInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetRegisterInfo<Service > StreamedService;
};

}  // namespace protos


#endif  // GRPC_Regulator_2eproto__INCLUDED
